// <auto-generated />
using FavSoccerPlayersApp.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FavSoccerPlayersApp.Migrations
{
    [DbContext(typeof(SoccerPlayersDbContext))]
    partial class SoccerPlayersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FavSoccerPlayersApp.Entities.SoccerPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("PreviousTeams")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SoccerPlayers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alphonso Davies",
                            Number = 19,
                            PreviousTeams = "Vancouver Whitecaps FC",
                            Team = "Bayern Munich"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Atiba Hutchinson",
                            Number = 13,
                            PreviousTeams = "FC Copenhagen, PSV Eindhove",
                            Team = "Beşiktaş"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jonathan David",
                            Number = 20,
                            PreviousTeams = "Gent",
                            Team = "Lille OSC"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cyle Larin",
                            Number = 17,
                            PreviousTeams = "Orlando City SC, Zulte Waregem",
                            Team = "Real Valladolid"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Milan Borjan",
                            Number = 1,
                            PreviousTeams = "Sivasspor, Ludogorets Razgrad",
                            Team = "Red Star Belgrade"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
